# Generated by Django 3.2.9 on 2022-07-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True, null=True, verbose_name='День месяца')),
                ('photo', models.IntegerField(blank=True, null=True, verbose_name='Фото')),
                ('video', models.IntegerField(blank=True, null=True, verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_list', models.IntegerField(verbose_name='месяц')),
                ('year_list', models.IntegerField(verbose_name='год')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Сток')),
                ('pseudo_name', models.CharField(default='Новый сток', max_length=32, verbose_name='Псевдоним')),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фото')),
                ('video', models.PositiveIntegerField(blank=True, null=True, verbose_name='Видео')),
                ('income', models.FloatField(blank=True, null=True, verbose_name='Доход')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_day', to='photos.day', verbose_name='Дата')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='photos.stock', verbose_name='Сток')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='stock_day', through='photos.StockCount', to='photos.Day', verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month', to='photos.month', verbose_name='Месяц'),
        ),
    ]
